# This workflow integrates ShiftLeft Inspect with GitHub
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft Inspect

on:
  pull_request:
  workflow_dispatch:

jobs:
  Inspect-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Analyze with Inspect
      run: ${GITHUB_WORKSPACE}/sl analyze --no-diagnostic --force --app ShiftLeftJS --tag branch=${GITHUB_REF} --js --cpg .
      env:
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: Create status check
      run: |
        URL="https://www.shiftleft.io/violationlist/ShiftLeftJS?apps=ShiftLeftJS&isApp=1"
        GH_CHECK_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs"
        curl -XPOST $GH_CHECK_URL -H "Authorization: Token ${GITHUB_TOKEN}" -H "accept: application/vnd.github.antiope-preview+json" -H "Content-Type: application/json" -d "{\"name\": \"ShiftLeft Inspect\", \"head_sha\": \"${GITHUB_REF}\", \"external_id\": \"ShiftLeftJS\", \"details_url\": \"${URL}\", \"status\": \"completed\", \"conclusion\": \"action_required\", \"output\": {\"title\": \"ShiftLeft Inspect Findings\", \"summary\": \"Visit ${URL} for the findings\"}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
